### ISSUE TITLE
Adicionar algoritmo de luhn

### ISSUE THREAD

**Issue by guilhermetavares** [MaisTodos/python-creditcard#10]
Para validar um cartão, normalmente é utilizado o algoritmo Luhn (!https://en.wikipedia.org/wiki/Luhn_algorithm)

**Comment by russianbb** [comment]
VALID_CARDS = {
    "visa": "4539578763621486",
    "master": "5369835519963014",
    "diners": "30346836403940",
    "elo": "5041756758046020",
    "amex": "373257135458763",
    "aura": "5078601870000127985",
    "hiper": "6062825303833679",
    "visaMask": "4532000000000000",
}
